koncert/Controllers/ConcertController.cs
using koncert.Models.Entities;
using koncert.Models.Repositories;
using koncert.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace koncert.Controllers
{
    public class ConcertController : Controller
    {
        private readonly IConcertRepository _concertRepository;
        private readonly ICategoryRepository _categoryRepository;
        
        public ConcertController(IConcertRepository concertRepository, ICategoryRepository categoryRepository) 
        { 
            _concertRepository = concertRepository;
            _categoryRepository = categoryRepository;   
        }

        public IActionResult List(string category)
        {
            IEnumerable<Concert> concerts;
            string? currentCategory;

            if (string.IsNullOrEmpty(category))
            {
                concerts = _concertRepository.AllConcerts.OrderBy(p => p.ConcertId);
                currentCategory = "Wszystkie";
            }
            else
            {
                concerts = _concertRepository.AllConcerts
                    .Where(p => p.Category.Name == category)
                    .OrderBy(p => p.ConcertId);

                currentCategory = _categoryRepository.AllCategories
                    .FirstOrDefault(c => c.Name == category)?.Name;
            }

            return View(new ConcertListViewModel(concerts, currentCategory));
        }

        public IActionResult Details(int id)
        {
            var concert = _concertRepository.GetConcertById(id);
            if (concert == null)
            {
                return NotFound();
            }
            return View(concert);
        }
    }
}

koncert/Controllers/ContactController.cs
using Microsoft.AspNetCore.Mvc;

namespace koncert.Controllers
{
    public class ContactController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

koncert/Controllers/ShoppingCartController.cs
using koncert.Models.Repositories;
using koncert.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace koncert.Controllers;

public class ShoppingCartController : Controller
{
    private readonly IConcertRepository _concertRepository;
    private readonly IShoppingCart _shoppingCart;

    public ShoppingCartController(IConcertRepository concertRepository, IShoppingCart shoppingCart)
    {
        _concertRepository = concertRepository;
        _shoppingCart = shoppingCart;
    }

    public ViewResult Index()
    {
        var items = _shoppingCart.GetShoppingCartItems();
        _shoppingCart.ShoppingCartItems = items;

        var shoppingCartViewModel = new ShoppingCartViewModel(_shoppingCart, _shoppingCart.GetShoppingCartTotal());

        return View(shoppingCartViewModel);
    }

    public RedirectToActionResult AddToShoppingCart(int concertId)
    {
        var selectedConcert = _concertRepository.AllConcerts.FirstOrDefault(p => p.ConcertId==concertId);
        if (selectedConcert != null)
        {
            _shoppingCart.AddToCart(selectedConcert);
        }
        return RedirectToAction("Index");
    }
    public RedirectToActionResult RemoveFromShoppingCart(int concertId)
    {
        var selectedConcert =_concertRepository.AllConcerts.FirstOrDefault(p=>p.ConcertId==concertId);
        if (selectedConcert != null)
        {
            _shoppingCart.RemoveFromCart(selectedConcert);
        }
        return RedirectToAction("Index");
    }

}

koncert/Views/Shared/_Carousel.cshtml
<div id="carousel" class="carousel slide">
    <div class="carousel-inner">
        <div class="carousel-item active">
            <img src="@Url.Content("~/Images/webp/car1.webp")" class="d-block w-100" alt="event" height="800px">
        </div>
        <div class="carousel-item">
            <img src="@Url.Content("~/Images/webp/car2.webp")" class="d-block w-100" alt="event" height="800px">
        </div>
        <div class="carousel-item">
            <img src="@Url.Content("~/Images/webp/car3.webp")" class="d-block w-100" alt="event" height="800px">
        </div>
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#carousel" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carousel" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
    </button>
</div>

koncert/Views/Shared/_ConcertCard.cshtml
@model Concert

<div class="col">
    <div class="card shadow-sm">
        <img class="bd-placeholder-img card-img-top"
             width="188"
             height="225"
             src="@Model.ImageThumbnailUrl"
             alt="@Model.Name">
        <div class="card-body">
            <h5 class="card-title">
                <a asp-controller="Concert"
                   asp-action="Details"
                   asp-route-id="@Model.ConcertId">
                    @Model.Name
                </a>
            </h5>
            <p class="card-text">@Model.Description.Name</p>
            <div class="d-flex justify-content-between align-items-center">
                <a href="#" class="btn btn-primary">@Model.Price.ToString("c")</a>
                <small class="text-body-secondary">@Model.Artist</small>
            </div>
            <div class="addToCart">
                <p class="button">
                    <a class="btn btn-secondary" 
                    asp-controller="ShoppingCart" 
                    asp-action="AddToShoppingCart" 
                    asp-route-concertId="@Model.ConcertId">
                        Kup Bilet
                    </a>

                </p>
            </div>
        </div>
    </div>
</div>

koncert/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="pl">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width">
    <title>Zostań na chwilę i poszukaj...</title>
    <meta name="description" content="">
    <link href="~/lib/bootstrap/css/bootstrap.css" rel="stylesheet">
    <script src="~/lib/jquery/jquery.min.js"></script>
    <script src="~/lib/bootstrap/js/bootstrap.js"></script>
    <script src="~/lib/jquery-validate/jquery.validate.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
</head>
<body>

    <partial name="_Nav" />

    <partial name="_Carousel" />

    <main class="album py-5 bg-body-tertiary">
        <div class="album py-5 bg-body-tertiary">
            <div class="container">
                @RenderBody()
                @RenderSection("Scripts", required: false)
            </div>
        </div>
    </main>

</body>
</html>

koncert/Views/Shared/_Nav.cshtml
<nav class="navbar bg-body-tertiary">
    <div class="container d-flex justify-content-between align-items-center">
        <a class="navbar-brand" asp-controller="Home" asp-action="Index">
            <img src="@Url.Content("~/Images/concert_logo.jpg")" alt="Zostań na chwilę i poszukaj..." style="width: 100px; height: auto;">
        </a>
        <ul class="navbar-nav d-flex flex-row justify-content-center">
            <li class="nav-item me-3">
                <a class="nav-link"
                   asp-controller="Home"
                   asp-action="Index">
                    GŁÓWNA
                </a>
            </li>

            <vc:category-menu></vc:category-menu>
            
            <li class="nav-item">
                <a class="nav-link" asp-controller="Contact" asp-action="Index">
                    KONTAKT
                </a>
            </li>
        </ul>
        <form class="d-flex" role="search">
            <input class="form-control me-2" type="search" placeholder="Szukaj" aria-label="Szukaj">
            <button class="btn btn-outline-success" type="submit">Szukaj</button>
        </form>
        <partial name="_LoginPartial"/>
        <vc:shopping-cart-summary></vc:shopping-cart-summary>
    </div>
</nav>